### ISSUE TITLE
finding the data

### ISSUE THREAD

**Issue by barthelemymp** [J-SNACKKB/FLIP#4]
Hello,

The procedure to run the benchmark is not really clear to me. I suppose I should run the notebooks of the collect_tasks. To do so I need a data folder not available here. How can I found this data ? 

Best

B

**Comment by sacdallago** [comment]
Hi @barthelemymp . Thanks for the interest. The raw data can be downloaded here: http://data.bioembeddings.com/public/FLIP

You should create a folder `data` in the root of your repository with the contents of this folder.
